package advisor.ai;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

/**
 * Calls Gemini to turn a recommendation's real, measured numbers into a
 * short natural-language explanation. Purely additive: the recommendation
 * itself is entirely measured (real CREATE INDEX + EXPLAIN ANALYZE), so
 * this class's only job is prose on top of an already-trustworthy result —
 * if GEMINI_API_KEY isn't set, or the call fails in any way, callers get a
 * clear fallback message instead of an exception, never a broken response.
 */
public class AiExplanationService {

    private static final String GEMINI_URL =
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=";

    private final String apiKey;
    private final HttpClient httpClient;
    private final ObjectMapper mapper = new ObjectMapper();

    public AiExplanationService() {
        this.apiKey = System.getenv("GEMINI_API_KEY");
        this.httpClient = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();
    }

    public List<String> generate(String context) {
        if (apiKey == null || apiKey.isBlank()) {
            return List.of("Gemini API key not found.");
        }

        try {
            String requestBody = buildRequestBody(context);

            HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(GEMINI_URL + apiKey))
                .timeout(Duration.ofSeconds(20))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                .build();

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

            return parseReasons(response.body());
        } catch (Exception e) {
            // Broad by design: this is a best-effort call to an external service
            // (network failure, timeout, malformed response, rate limit are all
            // equally "not our problem to surface as a 500" — the recommendation
            // itself doesn't depend on this succeeding).
            return List.of("Failed to generate explanation.");
        }
    }

    private String buildRequestBody(String context) {
        String prompt = "You are a PostgreSQL index tuning expert.\n\n"
            + "Below is a recommendation generated by an index advisor.\n\n" + context
            + "\n\nGenerate exactly 4 short bullet point explanations.\n"
            + "Return ONLY JSON in this format:\n"
            + "{\"reasons\": [\"...\", \"...\", \"...\", \"...\"]}";

        ObjectNode part = mapper.createObjectNode();
        part.put("text", prompt);

        ObjectNode content = mapper.createObjectNode();
        content.putArray("parts").add(part);

        ObjectNode requestBody = mapper.createObjectNode();
        requestBody.putArray("contents").add(content);

        return requestBody.toString();
    }

    private List<String> parseReasons(String responseBody) throws Exception {
        JsonNode result = mapper.readTree(responseBody);

        if (!result.has("candidates")) {
            return List.of("Gemini returned an error.");
        }

        String text = result.at("/candidates/0/content/parts/0/text").asText();

        int start = text.indexOf('{');
        int end = text.lastIndexOf('}');

        if (start < 0 || end < 0) {
            return List.of("Failed to parse Gemini response.");
        }

        JsonNode explanation = mapper.readTree(text.substring(start, end + 1));

        List<String> reasons = new ArrayList<>();

        for (JsonNode reason : explanation.get("reasons")) {
            reasons.add(reason.asText());
        }

        return reasons;
    }
}
