#define CPPHTTPLIB_OPENSSL_SUPPORT

#include "AIExplanationService.h"
#include "httplib.h"
#include "nlohmann/json.hpp"
#include <cstdlib>
#include <iostream>

using json = nlohmann::json;

AIExplanationService::AIExplanationService()
{
    const char *key = std::getenv("GEMINI_API_KEY");

    if (key)
    {
        apiKey_ = key;
    }
}

std::vector<std::string> AIExplanationService::generate(const std::string &advisorJson)
{
    auto st = std::chrono::steady_clock::now();
    std::vector<std::string> reasons;

    if (apiKey_.empty())
    {
        reasons.push_back("Gemini API key not found.");
        return reasons;
    }

    std::string prompt = "You are a PostgreSQL index tuning expert.\n\n"
                         "Below is a recommendation generated by and index advisor.\n\n" +
                         advisorJson + "\n\nGenerate exactly 4 short bullet point explanations.\n"
                                       "Return ONLY JSON in this format:\n"
                                       "{\n"
                                       "  \"reasons\": [\n"
                                       "    \"...\",\n"
                                       "    \"...\",\n"
                                       "    \"...\",\n"
                                       "    \"...\"\n"
                                       "  ]\n"
                                       "}";
    json requestBody;

    json part;
    part["text"] = prompt;

    json content;
    content["parts"] = json::array();
    content["parts"].push_back(part);

    requestBody["contents"] = json::array();
    requestBody["contents"].push_back(content);

    httplib::SSLClient client("generativelanguage.googleapis.com");

    std::string path = "/v1beta/models/gemini-flash-latest:generateContent?key=" + apiKey_;

    auto response = client.Post(path.c_str(), requestBody.dump(), "application/json");

    if (!response)
    {
        reasons.push_back("Failed to connect to Gemini.");
        return reasons;
    }

    json result = json::parse(response->body);

    if (!result.contains("candidates"))
    {
        std::cout << "No candidates found\n";
        std::cout << result.dump(4) << "\n";
        reasons.push_back("Gemini returned an error.");
        return reasons;
    }

    std::string text = result["candidates"][0]["content"]["parts"][0]["text"];

    auto start = text.find('{');
    auto end = text.rfind('}');
    if (start != std::string::npos && end != std::string::npos)
    {
        text = text.substr(start, end - start + 1);
    }

    try
    {
        json explanation = json::parse(text);

        for (const auto &reason : explanation["reasons"])
        {
            reasons.push_back(reason.get<std::string>());
        }
    }
    catch (...)
    {
        reasons.push_back("Failed to parse Gemini response. ");
    }

    auto e = std::chrono::steady_clock::now();
    return reasons;
}